### ISSUE TITLE
List the license explicitly in the (c) block.

### ISSUE THREAD

**Issue by JBontes** [d-mozulyov/BrainMM#2]
It's not clear to me under what license you're making the project available.  
It reads like the MIT license.  
It would help if you make explicit whether it is BSD, MIT, Mozilla etc.  
You might also want to dual license it so that more people can use it potentially.

**Comment by d-mozulyov** [comment]
Hello
It's MIT license

**Comment by d-mozulyov** [comment]
What should I do to the license it has been clear?
