### ISSUE TITLE
Error under Delphi7

### ISSUE THREAD

**Issue by mlcvista** [d-mozulyov/BrainMM#4]
{$ifdef MSWINDOWS}
const
BRAINMM_MARKER: array[1..18] of WideChar = 'Local\BrainMM_PID_';
HEX_CHARS: array[0..15] of WideChar = '0123456789ABCDEF';

Those lines return me a incompatible array's and string error, when I try to compile under Delphi7...
what is the consequence if we use used char instead of Widechar (with char, and OpenFileMapping, CreateFileMapping I can compile it...) ?

**Comment by d-mozulyov** [comment]
Hello!
Thanks for your issue

Wait a few weeks the next "master" release
Or just replace to the following:
```
const
  BRAINMM_MARKER: array[1..18] of WideChar = ('L','o','c','a','l','\','B','r','a','i','n','M','M','_','P','I','D','_');
  HEX_CHARS: array[0..15] of WideChar = ('0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F');
```
