### ISSUE TITLE
Compiling problems: E2201 error

### ISSUE THREAD

**Issue by Gronfi** [d-mozulyov/BrainMM#7]
Hi!
I'm creating a package that merely contains the brainmm.pas unit. When I compile it, next error appears: E2201 need imported data reference ($G) to access 'ReportMemoryLeaksOnShutdown' from unit 'BRainMM'. I have tried with that directive, also with the '{$IMPORTEDDATA ON}' after reading in the web some similar errors, but can't make it compile... :(
If I use the brainmm in a normal proyect (no packages), no problem. But when you use packages in any way, the problem appears and don't know how to solve it
Any idea what is happening?

**Comment by d-mozulyov** [comment]
Hi :)

> If I use the brainmm in a normal proyect (no packages), no problem.

Unfortunately, the BrainMM is not stable yet, that is why I do not recommend the library for commercial use. The development will be continued this winter.

 > Any idea what is happening?

Try to define "MANAGERFLAGSEMULATE" flag in your package. It is not quite correct, but hope will solve your problem

**Comment by Gronfi** [comment]
Hi again!
Thanks, this way the packages compile :)
And of course, thanks for your work
